export const authConstants={
     ADMIN_REGISTRATION_REQUEST : 'ADMIN_REGISTRATION_REQUEST',
     ADMIN_REGISTRATION_SUCCESS : 'ADMIN_REGISTRATION_SUCCESS',
     ADMIN_REGISTRATION_FAILURE : 'ADMIN_REGISTRATION_FAILURE',

     LOGIN_REQUEST : 'LOGIN_REQUEST',
     LOGIN_SUCCESS : 'LOGIN_SUCCESS',
     LOGIN_FAILURE : 'LOGIN_FAILURE',

     LOGOUT_REQUEST : 'LOGOUT_REQUEST',
     LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
     LOGOUT_FAILURE : 'LOGOUT_FAILURE'
}
export const categoryConstants = {
     CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
     CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
     CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

     GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
     GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
     GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
}
export const productConstants = {
     CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
     CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
     CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',

     GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
     GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
     GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
}


