export const authConstants={
     ADMIN_REGISTRATION_REQUEST : 'ADMIN_REGISTRATION_REQUEST',
     ADMIN_REGISTRATION_SUCCESS : 'ADMIN_REGISTRATION_SUCCESS',
     ADMIN_REGISTRATION_FAILURE : 'ADMIN_REGISTRATION_FAILURE',

     ADMIN_LOGIN_REQUEST : 'ADMIN_LOGIN_REQUEST',
     ADMIN_LOGIN_SUCCESS :'ADMIN_LOGIN_SUCCESS',
     ADMIN_LOGIN_FAILURE : 'ADMIN_LOGIN_FAILURE'
}
    


